[package]
name = "bevy_light_issue"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy_basic_camera = { git = "https://github.com/DGriffin91/bevy_basic_camera", rev = "cbba749a961e3eba9fb39c3ead5daf3e8da97530" }